version: '3.7'

services:
  reverse_nginx:
    container_name: reverse_nginx
    hostname: reverse_nginx
    image: nginx:1.23-alpine
    networks:
      - reverse
    ports:
      - "80:80"
    volumes:
      - ./reverse_proxy/conf/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  digital_planner:
    image: digital_planner:latest
    container_name: digital_planner
    restart: always
    env:
      DB_VERSION: 2022-latest
      DB_PORT_IN: 1433
      DB_PORT_OUT: 1433
      ACCEPT_EULA: Y
      MSSQL_SA_USER: ${{ secrets.MSSQL_SA_USER }}
      MSSQL_SA_PASSWORD: ${{ secrets.MSSQL_SA_PASSWORD }}
      MSSQL_PID: Developer
      DATA_VOLUME: /var/opt/mssql
      MSSQL_DB: ${{ secrets.MSSQL_DB }}
      MSSQL_USER: ${{ secrets.MSSSQL_USER }}
      MSSQL_PASSWORD: ${{ secrets.MSSQL_PASSWORD }}
      MSSQL_SERVER: mssql_server
      DRIVER: FreeTDS
      PROTOCOL: mssql+pyodbc
      OPTIONS: 'TDS_Version=8.0'
    networks:
    - db_network
    - reverse
    depends_on:
      mssql_server:
        condition: service_healthy

  mssql_server:
    image: mcr.microsoft.com/mssql/server:${DB_VERSION}
    container_name: ${MSSQL_SERVER}
    restart: always
    env:
      DB_VERSION: 2022-latest
      DB_PORT_IN: 1433
      DB_PORT_OUT: 1433
      ACCEPT_EULA: Y
      MSSQL_SA_USER: ${{ secrets.MSSQL_SA_USER }}
      MSSQL_SA_PASSWORD: ${{ secrets.MSSQL_SA_PASSWORD }}
      MSSQL_PID: Developer
      DATA_VOLUME: /var/opt/mssql
      MSSQL_DB: ${{ secrets.MSSQL_DB }}
      MSSQL_USER: ${{ secrets.MSSSQL_USER }}
      MSSQL_PASSWORD: ${{ secrets.MSSQL_PASSWORD }}
      MSSQL_SERVER: mssql_server
      DRIVER: FreeTDS
      PROTOCOL: mssql+pyodbc
      OPTIONS: 'TDS_Version=8.0'
    volumes:
     - ./mssql/initdb.sql:/init/initdb.sql
     - ./mssql/entrypoint.sh:/init/entrypoint.sh
     - ./mssql/initdb.sh:/init/initdb.sh
     - data:${DATA_VOLUME}
    networks:
     - db_network
    entrypoint:
     - /init/entrypoint.sh
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -U SA -P $MSSQL_SA_PASSWORD -S localhost -i /init/initdb.sql
      interval: 2s
      retries: 10
      start_period: 3s
      timeout: 3s


volumes:
  data:
    name: data

networks:
  db_network:
    driver: bridge
  reverse:
    driver: bridge
