version: '3.7'

services:
  digital_planner:
    image: digital_planner:${APP_VERSION}
    container_name: digital_planner
    restart: always
    env_file:
      - ./.env
    ports:
    - ${APP_PORT_OUT}:${APP_PORT_IN}
    volumes:
    - data:/src/app/instance
    networks:
     - mssql_net
    depends_on:
      mssql_server:
        condition: service_healthy
  mssql_server:
    image: mcr.microsoft.com/mssql/server:${DB_VERSION}
    container_name: ${MSSQL_SERVER}
    restart: always
    env_file:
      - ./.env
    ports:
     - "${DB_PORT_IN}:${DB_PORT_OUT}"
    volumes:
     - ./mssql/initdb.sql:/init/initdb.sql
     - ./mssql/entrypoint.sh:/init/entrypoint.sh
     - ./mssql/initdb.sh:/init/initdb.sh
     - data:${DATA_VOUME}
    networks:
     - mssql_net
    entrypoint:
     - /init/entrypoint.sh
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -U SA -P $MSSQL_SA_PASSWORD -S localhost -i /init/initdb.sql
      interval: 3s
      retries: 20
      start_period: 5s
      timeout: 5s


volumes:
  data:
    name: data

networks:
  reverse:
    driver: bridge
  mssql_net:
    driver: bridge